"""The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?"""
grid = [1,3]
x = 1
z = 1
y = 1
amnt = 1
found = False
last = 0
sqrt = 0

while found == False:
    while len(grid) < 500:
        grid.append(grid[len(grid)-1]+y)         
        y += 1
    else:
        for i in grid:
            sqrt = i**.5
            if i % 2 == 0:
                amnt = 2
                while z <= sqrt:
                    if i % z == 0:
                        amnt += 2
                        z += z - 1
                    if amnt >= 500:
                        print i
                        break
                    z += 1
            else:
                amnt= 2
                while z <= sqrt:
                    if i % z == 0:
                        amnt += 2
                        z += z - 1
                    if amnt >= 500:
                        print i
                        break
                    z += 1
    last = grid[len(grid)-1]
    del grid[:]
    grid.append(last)
    z = 1
    x += 500
print grid
